return function ()
	describe("Isotope", function()
		it("should boot", function()
			local Isotope = require(script.Parent)
			expect(Isotope).to.be.ok()
		end)
		it("should construct", function()
			local Isotope = require(script.Parent)
			local iso = Isotope.new({})
			expect(iso).never.to.equal(nil)
			iso:Destroy()
		end)
		it("should newindex", function()
			local Fusion = require(script.Parent.Parent:WaitForChild("coldfusion"))
			print("Reg")
			local Isotope = require(script.Parent)
			print("Making isotope")
			local iso = Isotope.new({})
			iso.Name = Fusion.Value("TestName")
			print("Iso", iso.Name)
			expect(iso).never.to.equal(nil)
			iso:Destroy()
		end)
	end)
end